# Created by 254n_m
# ChunkBan Exploit Fix
# Premission to bypass all restrictions
# chunkban.bypass

#Message to send the player when a chunk ban is prevented
Prevent-Message: '&6Your message here'

#Maximum ammount of tile entitys per chunk
TileEntity-Max: 512

#Maximum ammount of skulls per chunk
Skull-Max: 100
 